sudo: false

language: python

python:
 - "3.4"
 - "3.5"
 - "3.6"

addons:
  apt:
    packages:
      - libgdal1h
      - gdal-bin
      - libgdal-dev

install:
 - wget https://github.com/openmeteo/dickinson/archive/0.2.1.tar.gz
 - tar xzf 0.2.1.tar.gz
 - cd dickinson-0.2.1
 - ./configure
 - make
 - sudo make install
 - sudo ldconfig
 - cd ..

 - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'

 - pip install codecov
 - pip install -r requirements.txt
 - cp aira_project/settings/local-example.py aira_project/settings/local.py

script:
 - coverage run --include="./*" --omit="*/tests/*","*/tests.py" manage.py test -v2

after_success:
 - codecov
