# Generated by Django 2.2.12 on 2020-06-27 23:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aira', '0030_applied_irrigation_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrifield',
            name='telemetric_flowmeter_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agrifield',
            name='telemetric_flowmeter_type',
            field=models.CharField(blank=True, choices=[('LoRA_ARTA', 'LoRA_ARTA')], max_length=30, null=True),
        ),
    ]
