# Generated by Django 2.2.15 on 2020-08-29 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aira', '0031_kc_curve'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetricFlowmeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('LoRA_ARTA', 'LoRA_ARTA')], default='LoRA_ARTA', max_length=30)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('water_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=6.8, max_digits=5)),
                ('report_frequency_in_minutes', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='appliedirrigation',
            name='is_flowmeter_reported',
            field=models.BooleanField(default=False, verbose_name='Is automatically added by a flowmeter integration'),
        ),
        migrations.AddConstraint(
            model_name='appliedirrigation',
            constraint=models.UniqueConstraint(condition=models.Q(is_flowmeter_reported=True), fields=('is_flowmeter_reported', 'supplied_water_volume', 'timestamp'), name='unique_automatic_flowmeter_irrigations'),
        ),
        migrations.AddField(
            model_name='telemetricflowmeter',
            name='agrifield',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aira.Agrifield'),
        ),
    ]
