# Generated by Django 2.2.15 on 2020-10-10 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aira', '0032_kc_plantingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRA_ARTAFlowmeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('flowmeter_water_percentage', models.PositiveSmallIntegerField(help_text='Percentage of water that corresponds to the flowmeter (%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=6.8, max_digits=5)),
                ('report_frequency_in_minutes', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appliedirrigation',
            name='is_automatically_reported',
            field=models.BooleanField(default=False, verbose_name='Is automatically added by a flowmeter integration'),
        ),
        migrations.AddField(
            model_name='lora_artaflowmeter',
            name='agrifield',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aira.Agrifield'),
        ),
    ]
