# Generated by Django 2.2.15 on 2020-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aira', '0033_lora_artaflowmeter_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appliedirrigation',
            constraint=models.UniqueConstraint(condition=models.Q(is_automatically_reported=True), fields=('supplied_water_volume', 'timestamp', 'agrifield'), name='unique_automatic_flowmeter_irrigations'),
        ),
    ]
